# Files
PRESSURE_READER_FILE_NAME = 'TEST_Pressure_Values.txt'
PRESSURE_TYPES = ["PMAX", "PAINVALUE", "PAINTOLERANCE", "PATM"]
SCHEDULE_TYPES = ["PAIN", "NILL"]

HISTORY_LENGTH = 5

# Parameters
MAX_NUM_SCHEDULES = 8
MAX_NUM_PARAMETERS = 4

# Conversion lookup table

# STATES
CONNECT_CUFF_STATE = "CONNECT_CUFF"
IDLE_STATE = "IDLE"
ISOLATE_STATE = "ISOLATE"
ISOLATE_VENT_STATE = "ISOLATE_VENT"
ISOLATE_RELEASE_STATE = "ISOLATE_RELEASE"
ISOLATE_RESERVOIR_STATE = "ISOLATE_RESERVOIR"
LOAD_RESERVOIR_STATE = "LOAD_RESERVOIR"
NEW_ENTRY_STATE = "NEW_ENTRY"
RELEASE_STATE = "RELEASE"
VENT_STATE = "VENT"
ALL_STATES = [
        CONNECT_CUFF_STATE,
        IDLE_STATE,
        ISOLATE_STATE,
        ISOLATE_VENT_STATE,
        ISOLATE_RELEASE_STATE,
        ISOLATE_RESERVOIR_STATE,
        LOAD_RESERVOIR_STATE,
        NEW_ENTRY_STATE,
        RELEASE_STATE,
        VENT_STATE
    ]
