# Files
PRESSURE_READER_FILE_NAME = 'TEST_Pressure_Values.txt'
PRESSURE_TYPES = ["PMAX", "PAINH", "PAINL", "PATM"]
SCHEDULE_TYPES = ["PAIN", "NILL"]

# Parameters
MAX_NUM_SCHEDULES = 8
MAX_NUM_PARAMETERS = 4
