# Files
PRESSURE_READER_FILE_NAME = 'TEST_Pressure_Values.txt'
PRESSURE_TYPES = ["PMAX", "PAINVALUE", "PAINTOLERANCE", "PATM"]
SCHEDULE_TYPES = ["PAIN", "NILL"]


# Debug
DEBUG = True
HISTORY_LENGTH = 5

# Parameters
MAX_NUM_PHASES = 8
MAX_NUM_SCHEDULES = 4
MAX_NUM_PARAMETERS = 4

refresh_period = 0.1
