# Files
PRESSURE_READER_FILE_NAME = 'TEST_Pressure_Values.txt'
PRESSURE_TYPES = ["PMAX", "PAINVALUE", "PAINTOLERANCE", "PATM"]
SCHEDULE_TYPES = ["PAIN", "NILL"]

HISTORY_LENGTH = 5

# Parameters
MAX_NUM_SCHEDULES = 8
MAX_NUM_PARAMETERS = 4

# Conversion lookup table
